### ISSUE TITLE
dependecy on RegularizedLeastSquares

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MPIFiles.jl#15]
This dependency is due to some undocumented fields in the mdf files `/measurement/basisTransformation, `/measurement/isBasisTransformed` and `/measurement/basisIndices`. However I find that this does not really belong here, but instead into `MPIReco`.

**Comment by tknopp** [comment]
Thanks for raising this issue. I am not so sure about that one. That it is undocumented is clear since I first wanted to have a proof of principle, before I start adding it to the MDF.

The dependency on `RegularizedLeastSquares.jl` seems strange, but the dependency is on the linear transformations in there. We might split this off `RegularizedLeastSquares.jl` (makes sense) but that is a different topic. It is not completely straight forward, since that new package would need to be registered before we can move on.

Now we come to the core thing to discuss. Should the MPIFiles just deliver the raw data access (with raw data I mean what is contained in the file) or also some convenience functions. We here follow the concept that the MDF API functions (`measData` and so on) actually should only give the raw data access. The transformation of the data should be done in the high level API (e.g. `getMeasurements`, `getSystemMatrix`. In that particular case I have broken this pattern. I am not 100% sure why, but it might be because it was easier to implement this way. I am also not 100% happy about the `getSystemMatrix` in MPIFiles.jl and the `getSF` in MPIReco.jl.

Regarding whether this functionality belongs to `MPIFiles.jl` or `MPIReco.jl` I tend to think that it belongs to MPIFiles. `compressCalibMDF` would otherwise need to go to `MPIReco.jl`. The end user should not care if the content of an MDF is compressed or not.

**Comment by hofmannmartin** [comment]
With the addition of compression I understand why we need to keep the dependency for now.

> Now we come to the core thing to discuss. Should the MPIFiles just deliver the raw data access (with raw data I mean what is contained in the file) or also some convenience functions.

I think it is not a bad idea to have convenience funtions in `MPIFiles.jl`. However I would like to have some kind of separation on the source file level, where the raw data access functions, which implement the low level access API are in separate files than the convenience functions (e.g. `MDF.jl` and `MDFUtils.jl`). Moreover, I would suggest separating the experimental stuff that is not jet documented in the MDF specifications and sticking to the leading `_`-convention when introducing new fields.

Regarding the `getSF` functions I would like to have all functionality that can be counted as "convenience function" moved to `MPIFiles.jl` and keep only the stuff that is directly tied to the construction of some "reconstruction operator". Off course there is some room for debate on where to draw the line. E.g. is the reinterpretation of the data into a 2D Matrix convenience or already construction?

If we make decisions on these issues and implement them we could really bring forward the whole package. To this end it would be also a great idea to have some sort of written guideline which document these kind of decision.

**Comment by tknopp** [comment]
fixed in https://github.com/MagneticParticleImaging/MPIFiles.jl/commit/4ec1a7299697a30bea87e1f56b1f6749bbb78082
