### ISSUE TITLE
RawFile

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MPIFiles.jl#16]
Is the `struct RawFile` related stuff still required, or can it be replaced by `mmap`?

**Comment by tknopp** [comment]
It was recently re-added (https://github.com/MagneticParticleImaging/MPIFiles.jl/commit/c2b49833cc00127770fb2e1f5342883f213ff002) because of our performance issues. In the end it was not the cause of mmap. So in principle we could remove that stuff. If we do so, let us please keep a breadcrumb in the code pointing to that commit.

**Comment by hofmannmartin** [comment]
Let's make it so
