### ISSUE TITLE
Add support for field measurements

### ISSUE THREAD

**Issue by jonschumacher** [MagneticParticleImaging/MPIFiles.jl#36]
During our discussions on https://github.com/MagneticParticleImaging/MPIMeasurements.jl/pull/27, @jusack and me came across the [definition of the field measurement format](https://github.com/MagneticParticleImaging/MPIMeasurements.jl/blob/1d856c1c3db92b95ecc3b255c6a2890e1e91d4b6/src/Measurements/MagneticFieldSweepCurrents.jl#L72). Should this be moved over to MPIFiles or stay in MPIMeasurements? Do you see cases where there should be more information stored in the file than what is currently being done? I guess `timestamp`, `currents` and `fieldsError` could be optional.

**Comment by tknopp** [comment]
Good question. Originally I would have said: No it does not belong into MPIFiles, since MPIFiles ist only for storing MPI measurements. But right now I am not so sure anymore. If we do move it we do need some documentation on the available data formats (which we need anyway). Transfer functions are also stored in hdf5 in MPIFiles.
