### ISSUE TITLE
TOML file description for sequence

### ISSUE THREAD

**Issue by jonschumacher** [MagneticParticleImaging/MPIFiles.jl#37]
As discussed in https://github.com/MagneticParticleImaging/MPIMeasurements.jl/issues/22 we need a definition of a sequence in MPIMeasurements. Since this can be described in a quite abstract way, this is moved to MPIFIles.

The definition is currently only a bunch of structs (see PR #38) which can be read from a TOML file, but I would like to start a discussion here, whether I thought of all cases, before I start the next steps.

Needed steps for a full PR are now:
- [ ] Decide on the final definition
- [ ] Add tests
- [ ] Add documentation

**Comment by tknopp** [comment]
Thanks for pushing this Jonas. I just made a very quick review and think that in general this goes into the right direction. More concretely, I agree that we should have structs to define sequences. In order to dig deeper into this I think we really need some examples where one setups a sequence, runs it on the DummyDAC and stores the data into an MDF. I find it somewhat difficult to only judge on this based on the structs being defined here.

**Comment by jonschumacher** [comment]
Yeah, I fully understand that. It took me a while to sort out what I think are all the cases for MPI scanners that might be possible to build and I am very sure that I missed important cases. I guess this has to evolve together with my work on MPIMeasurements and then we can review and merge the PRs in conjunction.
